### PR TITLE
RED-1096: Add aviary.yaml

### PR DESCRIPTION
**Pull request by ghost**
#### Description

This adds an aviary.yaml config file.

@stevenosborne-wf

### CODE REVIEW

**Comment by aviary2-wf** [comment]
## Raven

Number of Findings: 1
- Watched file `aviary.yaml` added

As a result of the finding(s) listed above, a security review is required for this pull request.

**Comment by matthewsullivan-wf** [comment]
+1 security

**Comment by matthewlorimor-wf** [comment]
+1

**Comment by jeffreymelvin-wf** [comment]
+1

**Comment by ghost** [comment]
@Workiva/release-management-p

**Comment by teresarevious-wf** [comment]
RM +1

**Pull request merged**
